---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaas
  namespace: default
  labels:
    app: jaas
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: jaas
  template:
    metadata:
      labels:
        app: jaas
    spec:
      containers:
      - name: jaas
        image: jaas:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: jaas
  namespace: default
spec:
  selector:
    app: jaas
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jaas
  namespace: chplatform
spec:
  rules:
  - host: jaas.example.com
    http:
      paths:
      - backend:
          serviceName: jaas
          servicePort: 80
  tls:
  - hosts:
    - jaas.example.com
